use dummy_day_lib::dummy_day_mod;
include!(concat!(env!("OUT_DIR"), "/linker.rs"));

dummy_day_mod!(1);
dummy_day_mod!(2);
dummy_day_mod!(3);
dummy_day_mod!(4);
dummy_day_mod!(5);
dummy_day_mod!(6);
dummy_day_mod!(7);
dummy_day_mod!(8);
dummy_day_mod!(9);
dummy_day_mod!(10);
dummy_day_mod!(11);
dummy_day_mod!(12);
dummy_day_mod!(13);
dummy_day_mod!(14);
dummy_day_mod!(15);
dummy_day_mod!(16);
dummy_day_mod!(17);
dummy_day_mod!(18);
dummy_day_mod!(19);
dummy_day_mod!(20);
// dummy_day_mod!(21);
// dummy_day_mod!(22);
// dummy_day_mod!(23);
// dummy_day_mod!(24);
// dummy_day_mod!(25);